name: CI (Linux)

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang]
        include:          
          - compiler: clang
            cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libasound2-dev libxinerama-dev libxi-dev qt5-default ffmpeg
      - name: Install clang
        if: matrix.compiler == 'clang'
        run: sudo apt-get install -y clang
      - name: Build
        env:
          OVERRIDE_CC: ${{ matrix.cc }}
          OVERRIDE_CXX: ${{ matrix.cxx }}          
          TOOLS: 1
        run: make -j2
      - name: Validate
        run: ./mame64 -validate
      - uses: actions/upload-artifact@master
        with:
          name: mame64-linux-${{ matrix.compiler }}-${{ github.sha }}
          path: mame64
